apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: eyjo@megazone.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        route53:
          region: ap-northeast-2
          hostedZoneID: Z0009353343PVNDRV93BC
          accessKeyID: AKIA6G75DWZWBQTJNUUW
          secretAccessKeySecretRef:
            name: route53-secret
            key: secret-access-key
